title: 'Ymarillet.ninja - Blog tech & lifestyle'
default_lang: fr
author:
  name: 'Yohann M.'
  email: yohann.marillet@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Bienvenue sur mon blog tech & lifestyle ymarillet.ninja, partage de connaissances'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
