title: 'Ymarillet.ninja - Blog personnel de Yohann Marillet'
default_lang: fr
author:
  name: 'Yohann Marillet'
  email: yohann.marillet@gmail.com
taxonomies:
  - categories
  - technologies
metadata:
  description: 'Bienvenue sur mon blog personnel ymarillet.ninja, partage de connaissances, reflexions, découvertes ...'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
