version: "3.2"

services:
  nginx:
    env_file: nginx/.env
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/logs/nginx:/var/log/nginx
      - sources:/opt/sources/:ro
    networks:
      - "reverseproxy"
      - "default"

  php:
    image: php:fpm-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/php.ini:/usr/local/etc/php/php.ini:ro
      - sources:/opt/sources/

  data:
    env_file: data/.env
    build: ./data
    restart: "no"
    volumes:
      - sources:/opt/sources/

volumes:
  sources:

networks:
  reverseproxy:
    external:
      name: "reverseproxy_reverseproxy"
